/**
 * Single source of truth for the Shiki language allowlist used by the
 * SyntaxHighlighter and by Vite's dependency optimization.
 *
 * Keys are canonical language ids passed to `codeToHast` / used by
 * `getShikiLanguageForFile`. Values are the `shiki/langs/<value>.mjs` module
 * names, which may differ for aliases (e.g. `bash` loads `shellsession`).
 */
export const SHIKI_LANGUAGE_REGISTRY: Record<string, string> = {
  bash: "shellsession",
  batch: "batch",
  c: "c",
  clojure: "clojure",
  cpp: "cpp",
  csharp: "csharp",
  css: "css",
  dart: "dart",
  diff: "diff",
  dockerfile: "dockerfile",
  elixir: "elixir",
  erlang: "erlang",
  fsharp: "fsharp",
  go: "go",
  graphql: "graphql",
  groovy: "groovy",
  haskell: "haskell",
  hcl: "hcl",
  html: "html",
  http: "http",
  ini: "ini",
  java: "java",
  javascript: "javascript",
  json: "json",
  json5: "json5",
  jsx: "jsx",
  julia: "julia",
  kotlin: "kotlin",
  less: "less",
  lua: "lua",
  makefile: "makefile",
  markdown: "markdown",
  matlab: "matlab",
  nginx: "nginx",
  nix: "nix",
  "objective-c": "objective-c",
  ocaml: "ocaml",
  perl: "perl",
  php: "php",
  powershell: "powershell",
  properties: "properties",
  protobuf: "protobuf",
  python: "python",
  r: "r",
  regex: "regex",
  ruby: "ruby",
  rust: "rust",
  sass: "sass",
  scala: "scala",
  scss: "scss",
  shellsession: "shellsession",
  solidity: "solidity",
  sql: "sql",
  swift: "swift",
  toml: "toml",
  tsx: "tsx",
  typescript: "typescript",
  xml: "xml",
  yaml: "yaml",
};
